-- Supabase Usage Tracking Table Schema
-- Feature: 009-supabase-integration-use
-- Created: 2025-10-02
--
-- This table tracks Dev Tools button clicks in the Audio Protocol Wizard
-- for usage analytics. All data is retained indefinitely.

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create the adp_usage table
CREATE TABLE IF NOT EXISTS adp_usage (
  -- Primary key: Auto-generated UUID
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Button identification
  button_clicked_name TEXT NOT NULL,

  -- Timestamp when button was clicked (user timezone aware)
  button_clicked_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

  -- Input phrase (nullable - not all buttons have input)
  input_phrase TEXT,

  -- Response phrase (nullable - not all buttons generate responses)
  response_phrase TEXT,

  -- Complete result JSON from button function (nullable, flexible schema)
  result_json JSONB,

  -- Audit timestamp for record creation
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for query performance

-- Time-based queries (most common - analytics over time ranges)
CREATE INDEX IF NOT EXISTS idx_adp_usage_button_clicked_time
  ON adp_usage(button_clicked_time DESC);

-- Button-type filtering (e.g., "show all translate-phrase clicks")
CREATE INDEX IF NOT EXISTS idx_adp_usage_button_name
  ON adp_usage(button_clicked_name);

-- Composite index for combined filtering (button + time range)
CREATE INDEX IF NOT EXISTS idx_adp_usage_analytics
  ON adp_usage(button_clicked_name, button_clicked_time DESC);

-- JSONB GIN index for querying result_json contents (if needed for analytics)
CREATE INDEX IF NOT EXISTS idx_adp_usage_result_json
  ON adp_usage USING GIN (result_json);

-- Constraints

-- Button name must not be empty string
ALTER TABLE adp_usage
  ADD CONSTRAINT chk_button_name_not_empty
  CHECK (button_clicked_name != '');

-- Button clicked time cannot be in the future (allow 5 min clock skew tolerance)
ALTER TABLE adp_usage
  ADD CONSTRAINT chk_button_time_not_future
  CHECK (button_clicked_time <= NOW() + INTERVAL '5 minutes');

-- Comments for documentation

COMMENT ON TABLE adp_usage IS
  'Usage tracking for Dev Tools buttons in Audio Protocol Wizard. Records retained indefinitely for analytics.';

COMMENT ON COLUMN adp_usage.id IS
  'Unique identifier for each usage record (auto-generated UUID)';

COMMENT ON COLUMN adp_usage.button_clicked_name IS
  'Name of the Dev Tools button clicked (e.g., "randomize-all", "translate-phrase")';

COMMENT ON COLUMN adp_usage.button_clicked_time IS
  'Timestamp when user clicked the button (timezone-aware)';

COMMENT ON COLUMN adp_usage.input_phrase IS
  'Input phrase provided to button function (null if not applicable)';

COMMENT ON COLUMN adp_usage.response_phrase IS
  'Response phrase generated by button function (null if not applicable)';

COMMENT ON COLUMN adp_usage.result_json IS
  'Complete structured output from button function (JSONB for flexible querying)';

COMMENT ON COLUMN adp_usage.created_at IS
  'Audit timestamp for when record was inserted into database';

-- Row Level Security (RLS) Policies
-- Enable RLS on the table
ALTER TABLE adp_usage ENABLE ROW LEVEL SECURITY;

-- Policy: Allow INSERT from authenticated users only
CREATE POLICY "Allow authenticated inserts"
  ON adp_usage
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Policy: Allow SELECT for service role only (backend/admin access)
CREATE POLICY "Allow service role reads"
  ON adp_usage
  FOR SELECT
  TO service_role
  USING (true);

-- No UPDATE or DELETE policies - records are immutable (insert-only)

-- Sample queries for validation

-- Count clicks by button type
-- SELECT button_clicked_name, COUNT(*) as click_count
-- FROM adp_usage
-- GROUP BY button_clicked_name
-- ORDER BY click_count DESC;

-- Recent clicks (last 24 hours)
-- SELECT button_clicked_name, button_clicked_time, input_phrase, response_phrase
-- FROM adp_usage
-- WHERE button_clicked_time > NOW() - INTERVAL '24 hours'
-- ORDER BY button_clicked_time DESC;

-- Button usage over time (daily aggregates)
-- SELECT
--   DATE(button_clicked_time) as date,
--   button_clicked_name,
--   COUNT(*) as clicks
-- FROM adp_usage
-- WHERE button_clicked_time > NOW() - INTERVAL '30 days'
-- GROUP BY DATE(button_clicked_time), button_clicked_name
-- ORDER BY date DESC, clicks DESC;
