"""Test phrases for AI translation testing."""

ARBITRARY_PHRASES = [
    # Original 50 shorter phrases
    "A really chilled-out hip-hop track for studying.",
    "Aggressive, super-fast metal with cookie monster vocals.",
    "Sounds like a robot having a panic attack in a factory.",
    "Gentle, fingerpicked acoustic guitar, perfect for a rainy day.",
    "An 80s synth banger that would be in the movie *Top Gun*.",
    "Spooky, atmospheric music for a haunted house.",
    "A banger for the club with a fat, thumping kick drum.",
    "Slow, weepy blues guitar with a walking bassline.",
    "Gigantic, loud orchestra music for a superhero movie finale.",
    "A girl singing softly over a dreamy, lo-fi beat.",
    "Funky bassline and a four-on-the-floor beat, very disco.",
    "A grimey, distorted bass wobble you can feel in your chest.",
    "Music for driving through a neon city at 2 AM.",
    "An old-school boom-bap beat with a dusty jazz sample.",
    "A happy, upbeat pop song with sparkly synths and a female singer.",
    "The guitar sounds like a swarm of angry bees.",
    "A beautiful, sad piano piece that's very simple.",
    "That classic, hazy, stoned reggae sound with a deep bass.",
    "A triumphant horn fanfare to announce a king.",
    "Really complex, nerdy drumming with weird time signatures.",
    "A wall of fuzzy, chunky guitar noise.",
    "Whispering, spooky vocals over a sparse, cold soundscape.",
    "Total coffee shop vibes, very warm and inviting.",
    "A dark, pounding techno track for a warehouse rave.",
    "Uplifting trance music with a euphoric, soaring lead synth.",
    "Sounds like a video game from the 90s, very pixelated and fun.",
    "A mournful cello melody that feels very lonely.",
    "Energetic punk rock, fast and sloppy with shouted lyrics.",
    "Smooth jazz saxophone, the kind you hear in an elevator.",
    "A rambling, heartfelt folk song with a man and his guitar.",
    "The beat is kind of broken and stutters a lot.",
    "A huge, reverberating choir singing in a cathedral.",
    "A gritty, raw rock riff that's all swagger.",
    "The whole track is just a slowly building pad of sound.",
    "A playful, bouncy beat with a bubbly synth melody.",
    "Music that feels ancient and tribal, with lots of percussion.",
    "A sentimental country song about heartbreak with a twangy guitar.",
    "The bass is just a deep, continuous hum underneath everything.",
    "An angry rap song with a menacing, stripped-back beat.",
    "An opulent, rich string arrangement for a historical drama.",
    "Sounds like it was recorded on a cheap cassette tape, very muffled.",
    "A delicate, crystalline music box melody.",
    "The vocals are autotuned to sound robotic and futuristic.",
    "A chaotic, free-jazz freakout with squealing saxophones.",
    "A soulful R&B track with a velvety smooth electric piano.",
    "Music to meditate to, very calm and flowing.",
    "An epic, swashbuckling theme for a pirate adventure.",
    "The drums are really tight and punchy.",
    "A whimsical, slightly strange tune that feels like a circus.",
    "A powerful, belting female vocal over a simple pop-rock arrangement.",

    # Extended 50 longer, more complex phrases
    "A super laid-back and hazy lo-fi hip hop groove that feels like a rainy Sunday afternoon, with a dusty drum loop and a mournful, sampled piano melody.",
    "An absolutely blistering and relentless assault of thrash metal, driven by frantic, machine-gun drumming and a chainsaw guitar tone, all topped off with guttural, hard-to-understand growling vocals.",
    "This sounds like the inside of a glitching supercomputer, with stuttering, fragmented beats, robotic noises, and sharp, synthetic zaps that feel both chaotic and organized.",
    "A warm, intimate folk song featuring a lone male vocalist whose voice is almost a whisper, accompanied by the gentle, intricate fingerpicking of a steel-string acoustic guitar.",
    "Pure 80s nostalgia in a can, with a massive, gated reverb snare drum, a soaring and heroic synthesizer lead, and an electric guitar solo that's full of attitude.",
    "A truly unsettling and creepy soundscape that slowly builds tension using dissonant string textures, distant, ghostly whispers, and an almost sub-audible, deep drone.",
    "The ultimate feel-good disco anthem for a packed dancefloor, propelled by a funky, slapped bassline, shimmering strings, and a powerful female vocal diva.",
    "A deep, chest-rattling dubstep track where the grimy, wobbling bass synth is the main character, punctuated by a half-time beat with a sharp, cracking snare.",
    "This feels like the soundtrack to a cyberpunk future, a dark and propulsive synthwave piece with a steady, driving beat perfect for a late-night drive through a city of neon and rain.",
    "A classic boom-bap hip-hop instrumental with a raw, unpolished feel, built around a crunchy drum break sampled from an old funk record and a soulful electric piano harmony.",
    "A bright, cheerful, and incredibly upbeat indie-pop song that makes you want to dance, featuring a bouncy bassline, jangly guitars, and sparkly, layered vocal harmonies.",
    "This is just a massive wall of sound; a shoegaze track where the vocals are buried under layers of fuzzy, droning, and heavily distorted guitars that wash over you.",
    "A slow, smoldering blues number with a weeping, overdriven electric guitar that holds its notes forever, backed by a Hammond organ that fills out the sound with a warm glow.",
    "A colossal and majestic orchestral piece for a fantasy epic, with triumphant, blaring brass fanfares, the powerful swell of a full string section, and booming, thunderous percussion.",
    "A dreamy, atmospheric pop song where a breathy female vocalist sings over a bed of lush, ethereal synth pads and a simple, minimalistic electronic beat.",
    "The kind of swaggering, blues-infused hard rock with a central guitar riff that is so chunky and groovy it makes you nod your head instantly.",
    "A beautiful and heartbreakingly sad solo piano composition, where a simple, sparse melody is given emotional weight by the use of lots of space and quiet.",
    "This is the definition of chill, a classic roots reggae track with a relaxed, loping rhythm, a deep bassline that's more felt than heard, and echoey guitar stabs.",
    "A chaotic and dizzying experimental track that sounds like a radio skipping between ten different stations at once, full of static, vocal snippets, and jarring cuts.",
    "A powerful and somber piece for a string quartet, where a mournful cello melody weaves through the intricate and layered harmonies of the violins and viola.",
    "Feels like it belongs in a Quentin Tarantino movie, a surf rock instrumental with a twangy, reverb-drenched electric guitar playing a fast, catchy melody.",
    "The kind of new wave you'd hear at an 80s high school prom, with a slightly melancholic mood, a simple drum machine pattern, and a chorus-effected synth lead.",
    "An extremely raw and aggressive punk anthem that's barely two minutes long, characterized by three simple power chords, a frantic drum beat, and shouted, rebellious lyrics.",
    "A dark and moody trip-hop track with a slow, heavy beat, a mysterious bassline, and a haunting female vocal that sounds both distant and intimate at the same time.",
    "This is pure euphoria, a progressive trance track that builds for minutes with arpeggiated synths before releasing into a huge, uplifting drop with a soaring, beautiful melody.",
    "A quirky and playful piece of chiptune music that sounds like a boss battle from an old Nintendo game, featuring bubbly, synthesized melodies and fast-paced electronic percussion.",
    "A sprawling, psychedelic rock jam that evolves over ten minutes, starting quietly and building to a huge crescendo with a wailing guitar solo and crashing cymbals.",
    "The drums shuffle like a tired old man walking home in this cool jazz piece, providing a relaxed, unhurried foundation for a breathy, soulful saxophone solo.",
    "A waterfall of cascading piano notes creates a fluid, flowing texture in this minimalist classical piece, which is both meditative and emotionally stirring.",
    "An energetic bluegrass track that feels like a joyous hoedown, with incredibly fast banjo picking, a sprightly fiddle melody, and tight vocal harmonies.",
    "The main beat feels like it's intentionally broken and off-kilter, giving this experimental electronic track a jarring, unsettling energy that's hard to pin down.",
    "A rich and powerful gospel choir creates an overwhelming sense of spiritual joy, their layered voices soaring over a simple, rhythmic organ and hand claps.",
    "A gritty, unprocessed acoustic folk song that sounds like it was recorded live in one take, with the raw, honest voice of a singer-songwriter telling a story.",
    "The entire track is built on a single, deep, vibrating synthesizer drone that slowly changes character over time, creating a hypnotic, meditative experience.",
    "The kind of funky, sophisticated soul music from the 70s with a full horn section, a groovy bassline, and a silky smooth male lead vocal.",
    "This feels like an ancient, mystical ritual, using tribal percussion, a low, guttural human chant, and the sparse, hollow sound of a wooden flute.",
    "A sentimental and slightly cheesy power ballad, starting with a gentle piano before building to a huge chorus with a powerful, belting vocal and an epic guitar solo.",
    "The low end is just a pure, clean sub-bass frequency that rumbles continuously, providing a heavy, modern foundation for a sparse trap beat.",
    "An ice-cold and menacing rap track, where the rapper's aggressive, threatening lyrics are delivered over a stark, minimalistic beat made of little more than a kick, a snare, and a dark synth stab.",
    "An opulent and dramatic piece of Baroque classical music, full of intricate harpsichord runs, formal string arrangements, and a very sophisticated, elegant feel.",
    "Sounds like it was intentionally made to be lo-fi, with a muffled, compressed drum machine and a wobbly, out-of-tune synth melody that feels nostalgic.",
    "A delicate and fragile melody played on a celesta or glockenspiel gives this piece a childlike, innocent quality, like something from a fairy tale.",
    "The vocals are processed with extreme autotune and robotic effects, making the singer sound completely inhuman and futuristic over a hyperactive electronic beat.",
    "A complete sensory overload of free jazz, where every instrument seems to be soloing at once, creating a dense, chaotic, and challenging wall of sound.",
    "A sultry, late-night R&B groove with a creamy, rich Rhodes electric piano providing the harmony, a slow, sensual beat, and a breathy, intimate vocal performance.",
    "This track is designed for deep meditation, featuring the tranquil sounds of flowing water, gentle wind chimes, and a single, sustained, ethereal synth pad.",
    "An epic, cinematic adventure theme that immediately makes you think of pirates on the high seas, with a swashbuckling string melody and powerful, majestic brass.",
    "The drums on this funk track are incredibly tight, dry, and punchy, with the snare drum cracking through the mix to create an irresistible, danceable rhythm.",
    "A strange and whimsical instrumental that feels like a Danny Elfman film score for a Tim Burton movie, using pizzicato strings, tuba, and xylophone to create a quirky, mysterious mood.",
    "The song's emotional core is the raw, powerful female vocal, which belts out the chorus with incredible force over a relatively simple and standard pop-rock backing track."
]